// -i- Automatically generated by 'yarn link-routes', do not modify manually
export const routeManifest = {
  ['/bio']: 'BioScreen',
  ['/cv']: 'ResumeScreen',
  ['/']: 'BioScreen',
  ['/links']: 'BioScreen',
  ['/resume']: 'ResumeScreen',
  ['/cv/[slug]']: 'ResumeScreen',
  ['/resume/[slug]']: 'ResumeScreen',
} as const

export type KnownRoutes = keyof typeof routeManifest | (string & {})
