// -i- Automatically generated by 'yarn link-routes', do not modify manually
export const routeManifest = {
  ['/bio']: 'BioScreen',
  ['/cv']: 'ResumeScreen',
  ['/']: 'BioScreen',
  ['/links']: 'BioScreen',
  ['/resume']: 'ResumeScreen',
  ['/cv/[slug]/edit']: 'UpdateResumeScreen',
  ['/cv/[slug]']: 'ResumeScreen',
  ['/resume/[slug]']: 'ResumeScreen',
  ['/sign-in']: 'SignInScreen',
  ['/sign-up']: 'SignUpScreen',
} as const

// eslint-disable-next-line @typescript-eslint/ban-types
export type KnownRoutes = keyof typeof routeManifest | (string & {})
